#!/bin/bash
STATE=$(curl -sd '{"jsonrpc": "2.0", "id": 1, "method": "core.playback.get_state"}' http://localhost:6680/mopidy/rpc)
PLAYINGSTATE='{"jsonrpc": "2.0", "id": 1, "result": "playing"}'
echo $STATE
lastplayback=`cat lastplayback.state`
echo $lastplayback
if [ "$STATE" = "$PLAYINGSTATE" ]; then
  echo "playing" > lastplayback.state
  if [[ "$lastplayback" != "playing" ]]; then
     echo "I should start the stereo"
  fi
else
  echo "not_playing" > lastplayback.state
  if [[ "$lastplayback" != "not_playing" ]]; then
     echo "I should stop the stereo"
  fi
fi
